# Generated by Django 4.0.3 on 2022-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_radius', models.FloatField()),
                ('mean_texture', models.FloatField()),
                ('mean_perimeter', models.FloatField()),
                ('mean_area', models.FloatField()),
                ('mean_smoothness', models.FloatField()),
                ('mean_compactness', models.FloatField()),
                ('mean_concavity', models.FloatField()),
                ('mean_concave_points', models.FloatField()),
                ('mean_symmetry', models.FloatField()),
                ('mean_fractal_dimension', models.FloatField()),
                ('radius_error', models.FloatField()),
                ('texture_error', models.FloatField()),
                ('perimeter_error', models.FloatField()),
                ('area_error', models.FloatField()),
                ('smoothness_error', models.FloatField()),
                ('compactness_error', models.FloatField()),
                ('concavity_error', models.FloatField()),
                ('concave_points_error', models.FloatField()),
                ('symmetry_error', models.FloatField()),
                ('fractal_dimension_error', models.FloatField()),
                ('worst_radius', models.FloatField()),
                ('worst_texture', models.FloatField()),
                ('worst_perimeter', models.FloatField()),
                ('worst_area', models.FloatField()),
                ('worst_smoothness', models.FloatField()),
                ('worst_compactness', models.FloatField()),
                ('worst_concavity', models.FloatField()),
                ('worst_concave_points', models.FloatField()),
                ('worst_symmetry', models.FloatField()),
                ('worst_fractal_dimension', models.FloatField()),
                ('scaler', models.IntegerField()),
                ('prediction', models.PositiveIntegerField()),
            ],
        ),
    ]
