# Generated by Django 4.0.3 on 2022-08-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CancerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancer',
            name='scaler',
        ),
    ]
